CREATE SCHEMA IF NOT EXISTS MEETING_CALENDAR_DB;
USE MEETING_CALENDAR_DB;

CREATE TABLE USERS(
    USERNAME varchar(255) NOT NULL PRIMARY KEY,
    _PASSWORD varchar(255) NOT NULL,
    EXPIRED TINYINT DEFAULT FALSE,
    CREATE_DATE DATETIME DEFAULT NOW()
);

CREATE TABLE MEETING_CALENDARS(
    ID INT NOT null auto_increment primary key
    -- TODO
);



CREATE TABLE MEETINGS (
    ID INT NOT null auto_increment primary key
    -- TODO
);

