-- Create schema if not exists
CREATE SCHEMA IF NOT EXISTS MEETING_CALENDAR_DB;
USE MEETING_CALENDAR_DB;

-- Create USERS table
CREATE TABLE USERS
(
    USERNAME    VARCHAR(255) NOT NULL PRIMARY KEY,
    _PASSWORD   VARCHAR(255) NOT NULL,
    EXPIRED     TINYINT  DEFAULT FALSE,
    CREATE_DATE DATETIME DEFAULT NOW()
);

-- Create MEETING_CALENDARS table
CREATE TABLE MEETING_CALENDARS
(
    ID          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME    VARCHAR(255) NOT NULL,
    TITLE       VARCHAR(255) NOT NULL,
    CREATE_DATE DATETIME DEFAULT NOW(),
    FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME)
);

-- Create MEETINGS table
CREATE TABLE MEETINGS
(
    ID           INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE        VARCHAR(255) NOT NULL,
    START_TIME   DATETIME     NOT NULL,
    END_TIME     DATETIME     NOT NULL,
    _DESCRIPTION TEXT,
    CALENDAR_ID  INT          NOT NULL,
    CREATE_DATE  DATETIME DEFAULT NOW(),
    FOREIGN KEY (CALENDAR_ID) REFERENCES MEETING_CALENDARS (ID)
);